// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ServerSide.Models.EFModels;

public partial class Movie
{
    public int Id { get; set; }

    public int GenreId { get; set; }

    public int RatingId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Director { get; set; }

    public string Cast { get; set; }

    public int? RunTime { get; set; }

    public DateTime ReleaseDate { get; set; }

    public string PosterUrl { get; set; }

    public string TrailerUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? Updated { get; set; }

    public virtual Genre Genre { get; set; }

    public virtual ICollection<Price> Prices { get; set; } = new List<Price>();

    public virtual Rating Rating { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<Screening> Screenings { get; set; } = new List<Screening>();
}