// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ServerSide.Models.EFModels;

public partial class OrderItem
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int TicketId { get; set; }

    public string TicketName { get; set; }

    public int Price { get; set; }

    public int Qty { get; set; }

    public int SubTotal { get; set; }

    public string SeatNames { get; set; }

    public virtual Order Order { get; set; }

    public virtual Ticket Ticket { get; set; }
}