// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ServerSide.Models.EFModels;

public partial class Price
{
    public int Id { get; set; }

    public int MovieId { get; set; }

    public string SalesType { get; set; }

    public string TicketType { get; set; }

    public int ReservedSeats { get; set; }

    public int Price1 { get; set; }

    public virtual Movie Movie { get; set; }
}