// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ServerSide.Models.EFModels;

public partial class Screening
{
    public int Id { get; set; }

    public int MovieId { get; set; }

    public int TheaterId { get; set; }

    public DateOnly Televising { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual ICollection<SeatStatus> SeatStatuses { get; set; } = new List<SeatStatus>();

    public virtual Theater Theater { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}