// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ServerSide.Models.EFModels;

public partial class SeatStatus
{
    public int Id { get; set; }

    public int ScreeningId { get; set; }

    public int SeatId { get; set; }

    public string Status { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Screening Screening { get; set; }

    public virtual Seat Seat { get; set; }
}