// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ServerSide.Models.EFModels;

public partial class Seat
{
    public int Id { get; set; }

    public int TheaterId { get; set; }

    public string Row { get; set; }

    public string Number { get; set; }

    public bool IsDisabled { get; set; }

    public virtual ICollection<SeatStatus> SeatStatuses { get; set; } = new List<SeatStatus>();

    public virtual Theater Theater { get; set; }

    public virtual ICollection<TicketSeat> TicketSeats { get; set; } = new List<TicketSeat>();
}