// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ServerSide.Models.EFModels;

public partial class TicketSeat
{
    public int Id { get; set; }

    public int TicketId { get; set; }

    public int SeatId { get; set; }

    public virtual Seat Seat { get; set; }

    public virtual Ticket SeatNavigation { get; set; }
}